# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    chromium \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies and install chromium for playwright
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir . \
    && python -m playwright install chromium

CMD [ "playwright-server" ]
